debug: false
config:
  moneyCost: # only vault!
    enabled: true
    icon: "⛃"
    cost: 150000
  jewelsCost: # only SateJewels!
    enabled: true
    icon: "✦"
    cost: 99
  errorBuyingSound: BLOCK_ANVIL_PLACE
  successfulBuyingSound: ENTITY_PLAYER_LEVELUP

items:
  buy_slot:
    material: LIME_STAINED_GLASS_PANE
    displayName: "&b Покупка слота"
    lore:
      - " "
      - "&f Стоимость в осколках: &b$cost_jewels $jewels_icon &7(ЛКМ)"
      - "&f Стоимость в монетах: &b$cost_money $money_icon &7(ПКМ)"
      - " "
  closed_slot:
    material: GRAY_STAINED_GLASS_PANE
    displayName: "&c Закрытый слот!"
    lore:
      - " "
      - "&f Откройте сначала предыдущий слот!"
      - " "
  next_page:
    material: SPECTRAL_ARROW
    displayName: "&c Далее"
    enchanted: true
    lore:
      - ""
  back_page:
    material: SPECTRAL_ARROW
    displayName: "&c Обратно"
    lore:
      - ""

messages:
  ecoError: "&b(⚡)&f Ошибка экономики!"
  noArgs: "&b(⚡)&f У вас не хватает аргументов!"
  noMoney: "&b(⚡)&f У вас не хватает монеток!"
  noJewels: "&b(⚡)&f У вас не хватает осколков!"
  slotBuying: "&b(⚡)&f Слот для эндер-сундука успешно куплен!"
  reloadPlugin: "&b(⚡)&f Плагин перезагружен!"
  noPermission: "&b(⚡)&f У вас нет прав на это действие!"
  openEnderChest: "&b(⚡)&f Вы успешно открыли эндер-сундук игроку &b$player!"
  pageIsMax: "&b(⚡)&f Вы и так на максимальной странице!"
  pageIsMin: "&b(⚡)&f Вы и так на первой странице!"
  pageNotBought: "&b(⚡)&f Для начала откройте все слоты на данной странице!" # без права satenderchest.viewpages