name: SateEnderChest
version: '${project.version}'
main: progiple.satellite.sateenderchest.SateEnderChest
api-version: '1.16'
softdepend:
  - SateJewels
  - PlayerPoints
  - Vault
  - NBTAPI
  - LunaSpring
commands:
  sateenderchest:
    aliases:
      - ec
      - sec
      - sateec
      - sateender
      - sateenderc
      - sateechest
permissions:
  sateenderchest.open:
    default: true
  sateenderchest.admin:
    default: op
  sateenderchest.bypass:
    default: false
  sateenderchest.viewpages:
    default: false