debug: false
config:
  disablePutBackpacks: true # выключить возможность класть рюкзаки из плагина SateBackpacks в эндер-сундук?
  moneyCost: # only vault!
    enabled: true
    icon: "⛃"
    cost: 150000
  jewelsCost: # only SateJewels!
    enabled: true
    icon: "✦"
    cost: 99
  errorBuyingSound: BLOCK_ANVIL_PLACE
  successfulBuyingSound: ENTITY_PLAYER_LEVELUP
  itemsBlackList:
    - MATERIAL
    - BEDROCK
    - BARRIER

items:
  buy_slot:
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    displayName: "&x&2&A&8&8&F&8 Покупка слота"
    lore:
      - " "
      - "&f Стоимость в осколках: &x&2&A&8&8&F&8$cost_jewels $jewels_icon &7(ЛКМ)"
      - "&f Стоимость в монетах: &x&2&A&8&8&F&8$cost_money $money_icon &7(ПКМ)"
      - " "
      - "&x&2&A&8&8&F&8 ⁝ &fОткрывайте слоты за &x&2&A&8&8&F&8осколки"
      - "&x&3&D&9&2&F&7 ⁝ &x&2&A&8&8&F&8Или монеты&f, чтобы в ваш эндер"
      - "&x&4&F&9&B&F&6 ⁝ &fСундук можно было &x&2&A&8&8&F&8положить"
      - "&x&6&2&A&5&F&5 ⁝ &fКак можно &x&2&A&8&8&F&8больше предметов!"
      - " "
  closed_slot:
    material: GRAY_STAINED_GLASS_PANE
    displayName: "&c Закрытый слот!"
    lore:
      - " "
      - "&c ⁝ &fЧтобы купить &cданный слот,"
      - "&c ⁝ &fКупите сначала предыдущий!"
      - " "
  next_page:
    material: SPECTRAL_ARROW
    displayName: "&x&2&A&8&8&F&8 Следующая страница »"
    enchanted: true
    lore: []
  back_page:
    material: SPECTRAL_ARROW
    displayName: "&x&2&A&8&8&F&8 « Предыдущая страница"
    lore: []

messages:
  ecoError: "&x&2&A&8&8&F&8(⚡)&f Ошибка экономики!"
  noArgs: "&x&2&A&8&8&F&8(⚡)&f У вас не хватает аргументов!"
  noMoney: "&x&2&A&8&8&F&8(⚡)&f У вас не хватает монеток!"
  noJewels: "&x&2&A&8&8&F&8(⚡)&f У вас не хватает осколков!"
  slotBuying: "&x&2&A&8&8&F&8(⚡)&f Слот для эндер-сундука успешно куплен!"
  reloadPlugin: "&x&2&A&8&8&F&8(⚡)&f Плагин перезагружен!"
  noPermission: "&x&2&A&8&8&F&8(⚡)&f У вас нет прав на это действие!"
  openEnderChest: "&x&2&A&8&8&F&8(⚡)&f Вы успешно открыли эндер-сундук игроку &x&2&A&8&8&F&8$player!"
  pageIsMax: "&x&2&A&8&8&F&8(⚡)&f Вы и так на максимальной странице!"
  pageIsMin: "&x&2&A&8&8&F&8(⚡)&f Вы и так на первой странице!"
  pageNotBought: "&x&2&A&8&8&F&8(⚡)&f Для начала откройте все слоты на данной странице!" # без права sateenderchest.viewpages / sateenderchest.bypass
  itemInBlacklist: "&x&2&A&8&8&F&8(⚡)&f Этот предмет нельзя положить в эндер-сундук!" # без права sateenderchest.bypass