name: SateEnderChest
version: '1.0.7.2'
main: progiple.satellite.sateenderchest.SateEnderChest
api-version: '1.16'
softdepend:
  - SateJewels
  - PlayerPoints
  - Vault
  - NBTAPI
commands:
  sateenderchest:
    aliases:
      - sec
      - sateec
      - sateender
      - sateenderc
      - sateechest
permissions:
  sateenderchest.open:
    default: true
  sateenderchest.admin:
    default: op
  sateenderchest.bypass:
    default: false
  sateenderchest.viewpages:
    default: false